export const secteurList = {
  "1": "Agroalimentaire",
  "2": "Banque / assurance",
  "3": "Bois / papier / carton / imprimerie",
  "4": "BTP / matériaux de construction",
  "5": "Chimie / parachimie",
  "6": "Commerce / négoce / distribution",
  "7": "Edition / communication / multimedia",
  "8": "Electronique / électricité",
  "9": "Etudes et conseil",
  "10": "Industrie pharmaceutique",
  "11": "Informatique / télécommunications",
  "12": "Machines et équipements automobile",
  "13": "Métallurgie / travail du métal",
  "14": "Plastique / caoutchouc",
  "15": "Services aux entreprises",
  "16": "Textile / habillement / chaussures",
  "17": "Transport / logistique",
};
